[tool.black]
line-length = 120
include = '\.pyi?$'
force-exclude = '''
/(
    \.circleci
  | \.github
  | \.idea
  | \.pytest_cache
  | \.vscode
  | config
  | htmlcov
  | logs
  | telemetry_native
)/
'''

[tool.isort]
profile = "black" # black compatibility
multi_line_output = 3 # black compatibility
include_trailing_comma = true # black compatibility
force_grid_wrap = 0 # black compatibility
use_parentheses = true # black compatibility
ensure_newline_before_comments = true
line_length = 120
known_third_party = ["airflow"]
known_first_party = ["dags", "operators", "services", "subdags", "tests"]
